version: '3.9'
services:
  postgres:
    image: postgres:13-alpine
    container_name: menu-database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      # - ./.docker/postgres-data:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    container_name: menu-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=mcostacurta@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    depends_on:
      - postgres
  app:
    build: 
      dockerfile: Dockerfile-dev
    container_name: menu-api
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/food
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - .:/app
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  postgres-data:
