version: '3.9'
services:
  front-app:
    build: 
      dockerfile: Dockerfile-dev
    container_name: menu-frontend
    # user: "${UID}:${GID}"
    ports:
      - 3000:3000
    volumes:
      - .:/app